/*
 * hud_const.h
 *
 *  Created on: May 26, 2024
 *      Author: wx
 */

#ifndef ROBOT_CONFIG_HUD_CONSTANTS_H_
#define ROBOT_CONFIG_HUD_CONSTANTS_H_

#define GRAPHIC_NO_OP	0
#define GRAPHIC_ADD		1
#define GRAPHIC_MODIFY	2
#define GRAPHIC_DELETE	3

#define GRAPHIC_TYPE_LINE		0
#define GRAPHIC_TYPE_RECTANGLE	1
#define GRAPHIC_TYPE_CIRCLE		2
#define GRAPHIC_TYPE_ELLIPSE	3
#define GRAPHIC_TYPE_ARC		4
#define GRAPHIC_TYPE_FLOAT		5
#define GRAPHIC_TYPE_INT		6
#define GRAPHIC_TYPE_CHAR		7

#define GRAPHIC_COLOUR_OWN_COLOR	0
#define GRAPHIC_COLOUR_YELLOW		1
#define GRAPHIC_COLOUR_GREEN		2
#define GRAPHIC_COLOUR_ORANGE		3
#define GRAPHIC_COLOUR_PURPLISH_RED	4
#define GRAPHIC_COLOUR_PINK			5
#define GRAPHIC_COLOUR_CYAN			6
#define GRAPHIC_COLOUR_BLACK		7
#define GRAPHIC_COLOUR_WHITE		8

#define HUD_MAX_X 1920
#define HUD_MAX_Y 1080

#endif /* ROBOT_CONFIG_HUD_CONSTANTS_H_ */
